version: '3.8'

services:
  hmcts-dev-test-backend-app:
    build: .
    ports:
      - "3100:3100"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
    environment:
      SPRING_API_BASE_URL: http://hmcts-dev-test-backend-app:4000
    networks:
      - backend
networks:
  backend:
    external: true
    name: hmcts-network